price-aggregator-api:
  marketplace-config:
    ekatalog:
      url: https://ek.ua/ua/
      categories:
        selector: SELECT a.mainmenu-link | IGNORE 7,14 | TEXT | TRIM
      subcategories:
        - actions:
            - SELECT a.mainmenu-link | FILTER text=$(['category']) | FIRST | HOVER
            - SELECT li.mainmenu-item | FILTER selector=a.mainmenu-link,text=$(['category']) | FIRST | SELECT a.mainmenu-subitem:last-child | FIRST | CLICK
          selector: SELECT span.sub-katalogs-title | TEXT
        - actions:
            - SELECT a.mainmenu-link | FILTER text=$(['category']) | FIRST | HOVER
            - SELECT li.mainmenu-item | FILTER selector=a.mainmenu-link,text=$(['category']) | FIRST | SELECT a.mainmenu-subitem:last-child | FIRST | CLICK
            - SELECT span.sub-katalogs-title | FILTER text=$(['subcategory1']) | FIRST | CLICK
          selector: SELECT span.sub-katalogs-title | TEXT
        - actions:
            - SELECT a.mainmenu-link | FILTER text=$(['category']) | FIRST | HOVER
            - SELECT li.mainmenu-item | FILTER selector=a.mainmenu-link,text=$(['category']) | FIRST | SELECT a.mainmenu-subitem:last-child | FIRST | CLICK
            - SELECT span.sub-katalogs-title | FILTER text=$(['subcategory1']) | FIRST | CLICK
            - SELECT span.sub-katalogs-title | FILTER text=$(['subcategory2']) | ANY | CLICK
          selector: SELECT span.sub-katalogs-title | TEXT
      filters:
        actions:
          - SELECT a.mainmenu-link | FILTER text=$(['category']) | FIRST | HOVER
          - SELECT li.mainmenu-item | FILTER selector=a.mainmenu-link,text=$(['category']) | FIRST | SELECT a.mainmenu-subitem:last-child | FIRST | CLICK
          - SELECT span.sub-katalogs-title | FILTER text=$(['subcategory1']) | FIRST | CLICK
          - SELECT span.sub-katalogs-title | FILTER text=$(['subcategory2']) | ANY | CLICK
          - SELECT span.sub-katalogs-title | FILTER text=$(['subcategory3']) | ANY | CLICK
        selector: SELECT div.h2.h2-open | TEXT | JOIN with=1
        other:
          - SELECT ul.list>li.match-li-href | GROUP_BY parent_id | TEXT
      products:
        filters:
          index: 6
          template: SELECT li.match-li-href>label | FILTER text=$(['value_%d']) | ANY | CLICK
        self:
          actions:
            - SELECT a.mainmenu-link | FILTER text=$(['category']) | FIRST | HOVER
            - SELECT li.mainmenu-item | FILTER selector=a.mainmenu-link,text=$(['category']) | FIRST | SELECT a.mainmenu-subitem:last-child | FIRST | CLICK
            - SELECT span.sub-katalogs-title | FILTER text=$(['subcategory1']) | FIRST | CLICK
            - SELECT span.sub-katalogs-title | FILTER text=$(['subcategory2']) | ANY | CLICK
            - BY_ID minPrice_ | INPUT value=$(['minPrice'])
            - BY_ID maxPrice_ | INPUT value=$(['maxPrice'])
            - BY_ID match_submit | CLICK
            - SELECT div.page-num>a | FILTER text=$(['page']) | ANY | CLICK
          image-selector: SELECT .list-img>img | ATTRIBUTE src
          link-selector: SELECT a.model-short-title | UNION with=1 | ATTRIBUTE href
          price-img-selector: SELECT div.model-short-div>table>tbody>tr>td:nth-child(3) | SCREENSHOT | BASE64
          description-img-selector: SELECT div.model-short-div>table>tbody>tr>td:nth-child(2) | SCREENSHOT | BASE64
          title-selector: SELECT a.model-short-title | UNION with=1 | TEXT
          price-selector: SELECT div.model-price-range>a | TEXT
          pages-count-selector: SELECT div.page-num>a | TEXT | LAST
          other:
            - SELECT td.model-short-info>div:nth-child(1)>a
      search:
        ai-enabled: true
        actions:
          - BY_ID ek-search | INPUT value=$(['query'])
          - SELECT div.header_search_btn-submit>button | FIRST | CLICK
          - SELECT td.all_results>ul>li:first-child>div>div.search-cat-subcat>div:first-child>a | ANY | CLICK
        image-selector: SELECT .list-img>img | ATTRIBUTE src
        link-selector: SELECT a.model-short-title | UNION with=1 | ATTRIBUTE href
        price-img-selector: SELECT div.model-short-div>table>tbody>tr>td:nth-child(3) | SCREENSHOT | BASE64
        description-img-selector: SELECT div.model-short-div>table>tbody>tr>td:nth-child(2) | SCREENSHOT | BASE64
        title-selector: SELECT a.model-short-title | UNION with=1 | TEXT
        price-selector: SELECT div.model-price-range>a | TEXT
        pages-count-selector: SELECT div.page-num>a | TEXT | LAST
        other:
          - SELECT td.model-short-info>div:nth-child(1)>a
    hotline:
      url: https://hotline.ua/ua/catalog/
      categories:
        selector: SELECT .catalog-search__sections-item | TEXT
      subcategories:
        - selector: SELECT .catalog-sections__item | FILTER selector=.catalog-sections__name,text=$(['category']) | SELECT .catalog-sections-sub-catalog__title | TEXT | TRIM
        - selector: SELECT .catalog-sections__item | FILTER selector=.catalog-sections__title,text=$(['category']) | FIRST | SELECT .catalog-sections__sub-catalog | FILTER selector=.catalog-sections-sub-catalog__title,text=$(['subcategory1']) | FIRST | SELECT .catalog-sections-sub-catalog__item | TEXT
        - actions:
            - SELECT .catalog-sections__item | FILTER selector=.catalog-sections__title,text=$(['category']) | FIRST | SELECT .catalog-sections__sub-catalog | FILTER selector=.catalog-sections-sub-catalog__title,text=$(['subcategory1']) | FIRST | SELECT .catalog-sections-sub-catalog__link | FILTER text=$(['subcategory2']) | FIRST | CLICK
            - WAIT 2000
          selector: SELECT .section-navigation__link | TEXT
      filters:
        actions:
          - SELECT .catalog-sections__item | FILTER selector=.catalog-sections__title,text=$(['category']) | FIRST | SELECT .catalog-sections__sub-catalog | FILTER selector=.catalog-sections-sub-catalog__title,text=$(['subcategory1']) | FIRST | SELECT .catalog-sections-sub-catalog__link | FILTER text=$(['subcategory2']) | FIRST | CLICK
          - WAIT 2000
          - SELECT .section-navigation__link | FILTER text=$(['category3']) | ANY | CLICK
          - WAIT 2000
          - SELECT .modal__footer>div>button:nth-child(2) | ANY | CLICK
          - SELECT .filters-expand | ANY | CLICK
          - WAIT 1000
        selector: SELECT .sidebar-filter__header-title-text | IGNORE 0 | TEXT | TRIM | JOIN with=1
        other:
          - SELECT .filter-checklist__item | VISIBLE | GROUP_BY parent | TEXT
      products:
        filters:
          index: 8
          template: SELECT .sidebar-filters__item | FILTER selector=.sidebar-filter__header-title-text,text=$(['key_%d']) | ANY | SELECT .filter-checklist__item-name | FILTER text=$(['value_%d']) | ANY | CLICK
        self:
          actions:
            - SELECT .catalog-sections__item | FILTER selector=.catalog-sections__title,text=$(['category']) | FIRST | SELECT .catalog-sections__sub-catalog | FILTER selector=.catalog-sections-sub-catalog__title,text=$(['subcategory1']) | FIRST | SELECT .catalog-sections-sub-catalog__link | FILTER text=$(['subcategory2']) | FIRST | CLICK
            - SELECT .section-navigation__link | FILTER text=$(['category3']) | ANY | CLICK
            - SELECT .modal__footer>div>button:nth-child(2) | ANY | CLICK
            - WAIT 2000
            - SELECT .filters-expand | ANY | CLICK
            - SELECT .filter-price__range-field | BY_INDEX 0 | INPUT value=$(['minPrice'])
            - SELECT .filter-price__range-field | BY_INDEX 1 | INPUT value=$(['maxPrice'])
            - SELECT .filter-price__range-btn | FIRST | CLICK
            - WAIT 1000
            - SELECT .page | FILTER text=$(['page']) | ANY | CLICK alignToTop=true
          image-selector: SELECT .list-item__img>img,.promo-list-item__img>img | ATTRIBUTE src
          link-selector: SELECT .item-title,.promo-list-item__title | VISIBLE | ATTRIBUTE href
          price-img-selector: SELECT .list-item__value--overlay,.promo-list-item__value--overlay | SCREENSHOT | BASE64
          description-img-selector: SELECT .list-item__info,.promo-list-item__info | SCREENSHOT | BASE64
          title-selector: SELECT .item-title,.promo-list-item__title | VISIBLE | TEXT
          price-selector: SELECT .list-item__value--overlay>div>div | TEXT
          pages-count-selector: SELECT .page | TEXT | TRIM | LAST
      search:
        actions:
          - BY_ID autosuggest | SELECT div>input | FIRST | INPUT value=$(['query']) | ENTER
          - WAIT 2000
        image-selector: SELECT .list-item__img>img,.promo-list-item__img>img | ATTRIBUTE src
        link-selector: SELECT .item-title,.promo-list-item__title | VISIBLE | ATTRIBUTE href
        price-img-selector: SELECT .list-item__value--overlay,.promo-list-item__value--overlay | SCREENSHOT | BASE64
        description-img-selector: SELECT .list-item__info,.promo-list-item__info | SCREENSHOT | BASE64
        title-selector: SELECT .item-title,.promo-list-item__title | VISIBLE | TEXT
        price-selector: SELECT .list-item__value--overlay>div>div | TEXT
        pages-count-selector: SELECT .page | TEXT | TRIM | LAST
